/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsProjectileRouteImport } from './routes/experiments.projectile'
import { Route as ExperimentsCircuitRouteImport } from './routes/experiments.circuit'
import { Route as ExperimentsChemistryRouteImport } from './routes/experiments.chemistry'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsProjectileRoute = ExperimentsProjectileRouteImport.update({
  id: '/experiments/projectile',
  path: '/experiments/projectile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsCircuitRoute = ExperimentsCircuitRouteImport.update({
  id: '/experiments/circuit',
  path: '/experiments/circuit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsChemistryRoute = ExperimentsChemistryRouteImport.update({
  id: '/experiments/chemistry',
  path: '/experiments/chemistry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/experiments/chemistry': typeof ExperimentsChemistryRoute
  '/experiments/circuit': typeof ExperimentsCircuitRoute
  '/experiments/projectile': typeof ExperimentsProjectileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/experiments/chemistry': typeof ExperimentsChemistryRoute
  '/experiments/circuit': typeof ExperimentsCircuitRoute
  '/experiments/projectile': typeof ExperimentsProjectileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/experiments/chemistry': typeof ExperimentsChemistryRoute
  '/experiments/circuit': typeof ExperimentsCircuitRoute
  '/experiments/projectile': typeof ExperimentsProjectileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/experiments/chemistry'
    | '/experiments/circuit'
    | '/experiments/projectile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/experiments/chemistry'
    | '/experiments/circuit'
    | '/experiments/projectile'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/experiments/chemistry'
    | '/experiments/circuit'
    | '/experiments/projectile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ExperimentsChemistryRoute: typeof ExperimentsChemistryRoute
  ExperimentsCircuitRoute: typeof ExperimentsCircuitRoute
  ExperimentsProjectileRoute: typeof ExperimentsProjectileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/projectile': {
      id: '/experiments/projectile'
      path: '/experiments/projectile'
      fullPath: '/experiments/projectile'
      preLoaderRoute: typeof ExperimentsProjectileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/circuit': {
      id: '/experiments/circuit'
      path: '/experiments/circuit'
      fullPath: '/experiments/circuit'
      preLoaderRoute: typeof ExperimentsCircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/chemistry': {
      id: '/experiments/chemistry'
      path: '/experiments/chemistry'
      fullPath: '/experiments/chemistry'
      preLoaderRoute: typeof ExperimentsChemistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ExperimentsChemistryRoute: ExperimentsChemistryRoute,
  ExperimentsCircuitRoute: ExperimentsCircuitRoute,
  ExperimentsProjectileRoute: ExperimentsProjectileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
